import NavBar from '../Components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../Components/Footer'
import AuthProvider from '../Components/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'uiVerse',
  description: 'Generated by ChatGPT',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="bg-[#22272E]">
      <AuthProvider>
      <NavBar />
              {children}
        
        <Footer />
        </AuthProvider>
        </body>
    </html>
  )
}
